version: '3'

services:
  web:
    image: nginx:alpine
    container_name: tchoupi-web
    ports:
      - "8090:8090"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx:/etc/nginx/conf.d:ro
    restart: unless-stopped
