services:
  tchoupi-web:
    build:
      context: .
    image: tchoupi-audiobook-player:latest
    pull_policy: build
    ports:
      - "${TCHOUPI_HTTP_PORT:-8090}:8090"
    restart: unless-stopped
